# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/client/utils.ipynb.

# %% auto 0
__all__ = ['strip_accents', 'clean_file_name']

# %% ../nbs/client/utils.ipynb 5
def strip_accents(text_str: str) -> str:
    return "".join(
        c
        for c in unicodedata.normalize("NFD", text_str)
        if unicodedata.category(c) != "Mn"
    )

# %% ../nbs/client/utils.ipynb 8
def clean_file_name(file_name: str):
    clean_name = file_name.strip().replace(" ", "_")  # Replace with underscore
    clean_name = strip_accents(clean_name)

    pattern = "[^0-9a-zA-Z_\s]+"

    return re.sub(pattern, "", clean_name)
