project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
    - text: "projects"
      href: projects/index.qmd
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]